version: 1.0.{build}
pull_requests:
 do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /(Created|Update).*\.(png|jpg|jpeg|bmp|gif|md)/
skip_branch_with_pr: true
environment:
  SONAR_TOKEN: 
    secure: /a1k6MVBObLOM5paiNyCBAVgYtfX8cj+e3+FTFiu74tJWbEZbh2jAj5V0e6P4BVI
dotnet_csproj: 
  patch: true 
  file: '**\*.csproj' 
  version: '1.0.{build}' 
  package_version: '1.0.{build}' 
  assembly_version: '1.0.{build}'
  file_version: '1.0.{build}'
  informational_version: '1.0.{build}'
before_build:
- cmd: nuget restore
- cmd: choco install opencover.portable
- cmd: choco install codecov
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
build_script:
 - dotnet tool install --global dotnet-sonarscanner
 - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & 
  dotnet sonarscanner begin 
 /k:"guibranco_PriceZ" 
 /o:"guibranco-github" 
 /d:sonar.host.url="https://sonarcloud.io" 
 /d:sonar.login="$env:SONAR_TOKEN" 
 /v:"$env:APPVEYOR_BUILD_NUMBER" 
 /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" 
 /d:sonar.coverage.exclusions="PriceZ.Tests/**,**/*Tests.cs" 
 /d:sonar.cs.opencover.reportsPaths="$env:CD\Tests\PriceZ.Tests\coverage.opencover.xml" }'
 - dotnet build
 - ps: dotnet test .\Tests\PriceZ.Tests\PriceZ.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
 - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN" }'
 - codecov -f "Tests\PriceZ.Tests\coverage.opencover.xml"
after_build:
- xcopy %CD%\Src\PriceZ\bin\Release\netstandard2.0\*.* %CD%\Build\
- copy %CD%\Src\PriceZ\bin\Release\PriceZ.1.0.%APPVEYOR_BUILD_NUMBER%.nupkg PriceZ.%APPVEYOR_BUILD_VERSION%.nupkg
- rd /s /q %CD%\Src\PriceZ\bin\Release\
- cd %CD%
- 7z a -tzip -mx9 "PriceZ.%APPVEYOR_BUILD_VERSION%.zip" Build
artifacts:
- path: PriceZ.%APPVEYOR_BUILD_VERSION%.zip
  name: ZipFile
- path: PriceZ.%APPVEYOR_BUILD_VERSION%.nupkg
  name: Package
deploy:
- provider: Environment
  name: NuGet
  on:
   branch: master
  artifact: Package
- provider: GitHub
  on:
   branch: master
  tag: $(appveyor_build_version)
  auth_token:
    secure: VgYYJdvNLy/n9/uxxlaF0bMpIIrVxCb+dGr66U9nWfPWSN2ySdfuilO8klAw0uvF
  force_update: true
  artifact: ZipFile